language: scala
sudo: false
scala:
- 2.12.8
- 2.11.12
- 2.13.0-RC2
script:
- if [[ $TRAVIS_SCALA_VERSION == "2.13.0-RC2" ]] ; then git clone https://github.com/typelevel/kind-projector.git && cd kind-projector && git checkout v0.10.0 && sbt "++${TRAVIS_SCALA_VERSION}!" publishLocal && cd .. ; fi
- sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck "++ ${TRAVIS_SCALA_VERSION}!" test example/compile:runAll
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
matrix:
  include:
  - scala: 2.12.8
    jdk: openjdk11
    dist: xenial
  - scala: SCALA_NATIVE
    sudo: required
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.8/scripts/travis_setup.sh | bash -
    script:
    - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck native/test
